### ISSUE TITLE
Ubiety use in MySQL.Data

### ISSUE THREAD

**Issue by 3x0dv5** [ubiety/Ubiety.Dns.Core#11]
Hi, I am having a bit of trouble understanding if it is OK to use Ubiety.Dns.Core in a close source project, I am not going to use it directly, but by importing MySQL.Data it also imports Ubiety.Dns.Core. Now the problem is that in the license disclaimer of MySQL.Data says that Ubiety.Dns.Core is MIT

[nuge of MySqL.Data](https://www.nuget.org/packages/MySql.Data)
[MySql.Data](https://downloads.mysql.com/docs/licenses/connector-net-8.0-gpl-en.pdf)

![image](https://user-images.githubusercontent.com/250271/87227689-a8a23400-c394-11ea-9ad3-c6361bda1a76.png)

, but on the Ubiety's github says that is GPL3, although the repo (https://github.com/ubiety/Ubiety.Dns.Core) where this is mentioned is a fork of (https://github.com/ghuntley/Heijden.Dns) which mentions the project to be MIT.

[Ubiety.Dns.Core github](https://github.com/ubiety/Ubiety.Dns.Core)
![image](https://user-images.githubusercontent.com/250271/87227771-0afb3480-c395-11ea-9df2-2401942dc9db.png)

So... can Ubiety.Dns.Core be included, even if indirectly, in a closed source project?

**Comment by coder2000** [comment]
They are using a version that is still covered under MIT so it should be fine, and after realizing there is an issue with some of my other projects the license will probably be reverting to MIT anyway.
