### ISSUE TITLE
Upgraded to the latest version now I get no results

### ISSUE THREAD

**Issue by mjanulaitis** [ubiety/Ubiety.Dns.Core#36]
**Describe the bug**
Upgraded to the latest version now I get no results.  No code changes were made.

**To Reproduce**
var resolver = ResolverBuilder.Begin()
                .AddDnsServer(host.Name)
                .SetTimeout(1000)
                .EnableCache()
                .SetRetries(3)
                .UseRecursion()
                .Build();

        var response = resolver.Query(model.TestHost, (Ubiety.Dns.Core.Common.QuestionType)model.QuestionType, (Ubiety.Dns.Core.Common.QuestionClass)model.QuestionClass);
        if (response == null)
            throw new Exception(Resources.TEMPLATE_DNS_NO_RESPONSE);

**Expected behavior**
I should be getting back an answer.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Nuget Version 4.2.2

Rolling back to version 4.2.0 resolves the issue.

**Comment by Sabbi** [comment]
Same/similar issue here.

With 4.2.2, I do get a FormErr only:

[Ubiety.Dns.Core.Resolver::Debug] Received CNAME query for github.com
[Ubiety.Dns.Core.Resolver::Debug] Searching cache for question...
[Ubiety.Dns.Core.Resolver::Debug] Sending request to server...
[Ubiety.Dns.Core.Resolver::Debug] Starting TCP request...
[Ubiety.Dns.Core.Resolver::Debug] Attempt 1 of 3...
[Ubiety.Dns.Core.Resolver::Debug] Connecting to 8.8.8.8...
[Ubiety.Dns.Core.Resolver::Debug] Sending request to server...
[Ubiety.Dns.Core.Resolver::Debug] Building response...
[Ubiety.Dns.Core.Response::Debug] Received information from server
[Ubiety.Dns.Core.Resolver::Debug] Error from server - FormErr

Same everything, but with 4.2.1:

[Ubiety.Dns.Core.Resolver::Debug] Received CNAME query for github.com
[Ubiety.Dns.Core.Resolver::Debug] Searching cache for question...
[Ubiety.Dns.Core.Resolver::Debug] Sending request to server...
[Ubiety.Dns.Core.Resolver::Debug] Starting TCP request...
[Ubiety.Dns.Core.Resolver::Debug] Attempt 1 of 3...
[Ubiety.Dns.Core.Resolver::Debug] Connecting to 8.8.8.8...
[Ubiety.Dns.Core.Resolver::Debug] Sending request to server...
[Ubiety.Dns.Core.Resolver::Debug] Building response...
[Ubiety.Dns.Core.Response::Debug] Received information from server
[Ubiety.Dns.Core.Response::Debug] Adding questions...

**Comment by mjanulaitis** [comment]
No updates.  It seems this repository is dead :(.  I guess we all need to branch our own from 4.2.0 and maintain the library in our own repositories.  Bummer.  @realslacker do you have a reproduceable scenario with TXT records?

**Comment by tjhlansbergen** [comment]
I think this PR should fix it, @coder2000 could you look into that? 
https://github.com/ubiety/Ubiety.Dns.Core/pull/47

**Comment by EdwinVanVliet** [comment]
Created a new PR for this.

https://github.com/ubiety/Ubiety.Dns.Core/pull/51

**Comment by cornerbowlsoftware** [comment]
> Created a new PR for this.
> 
> #51

So sad it looks like this repo is stale.

**Comment by coder2000** [comment]
Merged
