### ISSUE TITLE
Ubiety.Dns.Core.dll is built in debug mode

### ISSUE THREAD

**Issue by tphaseitx** [ubiety/Ubiety.Dns.Core#7]
I try to publish my WPF application to Windows Store and after verification, I get this error. 

>> "Ubiety.Dns.Core.dll is built in debug mode"

I had installed the NuGet package MySql.Data 8.10.19 from Oracle.

Please advice! Thank You!

**Comment by coder2000** [comment]
Are you using Mysql.Data in your application?

**Comment by tphaseitx** [comment]
Yes..

**Comment by coder2000** [comment]
They made some changes to support .NET 4.5.2 and compiled their version. I would recommend opening an issue with them and recommend they open a pull request so I can merge their changes.

**Comment by tphaseitx** [comment]
Can you please help me with a link?

**Comment by coder2000** [comment]
https://bugs.mysql.com/

**Comment by tphaseitx** [comment]
I did that, but the problem with the Ubiety.Dns.Core continues. I had removed the reference of Ubiety.Dns.Core that was installed with the MySQL.Data package,

And installed the official Ubiety.Dns.Core package from NuGet, version 2.5.0.

I don't get that error anymore, but I get this:

Debug configuration test

FAILED
Debug configuration
Error Found: The debug configuration test detected the following errors:

The binary System.Globalization.Calendars.dll is built in debug mode.
The binary System.Threading.Tasks.Parallel.dll is built in debug mode.
The binary System.Xml.XmlDocument.dll is built in debug mode.
The binary System.Diagnostics.FileVersionInfo.dll is built in debug mode.
The binary System.IO.FileSystem.DriveInfo.dll is built in debug mode.
The binary System.Net.Ping.dll is built in debug mode.
The binary System.ComponentModel.Primitives.dll is built in debug mode.
The binary System.Net.NameResolution.dll is built in debug mode.
The binary System.ComponentModel.dll is built in debug mode.
The binary System.Runtime.InteropServices.dll is built in debug mode.
The binary System.Diagnostics.Process.dll is built in debug mode.
The binary System.Collections.Concurrent.dll is built in debug mode.
The binary System.Reflection.Primitives.dll is built in debug mode.
The binary System.Text.Encoding.dll is built in debug mode.
The binary System.Reflection.dll is built in debug mode.
The binary System.IO.UnmanagedMemoryStream.dll is built in debug mode.
The binary System.IO.IsolatedStorage.dll is built in debug mode.
The binary System.Net.WebSockets.Client.dll is built in debug mode.
The binary System.Resources.Reader.dll is built in debug mode.
The binary System.Linq.Parallel.dll is built in debug mode.
The binary System.Collections.dll is built in debug mode.
The binary System.Linq.dll is built in debug mode.
The binary System.Diagnostics.Contracts.dll is built in debug mode.
The binary System.Diagnostics.Tools.dll is built in debug mode.
The binary System.Collections.NonGeneric.dll is built in debug mode.
The binary System.Linq.Expressions.dll is built in debug mode.
The binary System.Runtime.Handles.dll is built in debug mode.
The binary System.Net.Security.dll is built in debug mode.
The binary System.Threading.Timer.dll is built in debug mode.
The binary System.ComponentModel.EventBasedAsync.dll is built in debug mode.
The binary System.Net.WebHeaderCollection.dll is built in debug mode.
The binary System.IO.FileSystem.Watcher.dll is built in debug mode.
The binary Ubiety.StyleCop.dll is built in debug mode.
The binary System.Runtime.CompilerServices.VisualC.dll is built in debug mode.
The binary Microsoft.Win32.Primitives.dll is built in debug mode.
The binary System.Runtime.Extensions.dll is built in debug mode.
The binary System.Text.Encoding.Extensions.dll is built in debug mode.
The binary System.Security.Principal.dll is built in debug mode.
The binary System.Globalization.dll is built in debug mode.
The binary System.ObjectModel.dll is built in debug mode.
The binary System.Collections.Specialized.dll is built in debug mode.
The binary System.IO.Compression.ZipFile.dll is built in debug mode.
The binary System.AppContext.dll is built in debug mode.
The binary System.Diagnostics.TraceSource.dll is built in debug mode.
The binary System.Security.Claims.dll is built in debug mode.
The binary System.Console.dll is built in debug mode.
The binary System.IO.Pipes.dll is built in debug mode.
The binary System.Linq.Queryable.dll is built in debug mode.
The binary System.Security.Cryptography.Csp.dll is built in debug mode.
The binary System.Security.Cryptography.Primitives.dll is built in debug mode.
The binary System.IO.dll is built in debug mode.
The binary System.Dynamic.Runtime.dll is built in debug mode.
The binary System.Net.NetworkInformation.dll is built in debug mode.
The binary System.Security.Cryptography.X509Certificates.dll is built in debug mode.
The binary System.Resources.Writer.dll is built in debug mode.
The binary System.Net.Primitives.dll is built in debug mode.
The binary System.Net.Requests.dll is built in debug mode.
The binary System.Runtime.Serialization.Formatters.dll is built in debug mode.
The binary System.Runtime.Numerics.dll is built in debug mode.
The binary System.Xml.XmlSerializer.dll is built in debug mode.
The binary System.Resources.ResourceManager.dll is built in debug mode.
The binary System.IO.FileSystem.dll is built in debug mode.
The binary System.ComponentModel.TypeConverter.dll is built in debug mode.
The binary System.Text.RegularExpressions.dll is built in debug mode.
The binary System.Diagnostics.TextWriterTraceListener.dll is built in debug mode.
The binary System.Threading.Thread.dll is built in debug mode.
The binary System.Drawing.Primitives.dll is built in debug mode.
The binary System.IO.MemoryMappedFiles.dll is built in debug mode.
The binary System.Threading.dll is built in debug mode.
The binary System.Xml.XDocument.dll is built in debug mode.
The binary System.Net.WebSockets.dll is built in debug mode.
The binary System.Diagnostics.Debug.dll is built in debug mode.
The binary System.Security.Cryptography.Encoding.dll is built in debug mode.
The binary System.Xml.XPath.dll is built in debug mode.
The binary System.Runtime.Serialization.Json.dll is built in debug mode.
The binary System.Xml.ReaderWriter.dll is built in debug mode.
The binary System.Reflection.Extensions.dll is built in debug mode.
The binary System.Threading.Tasks.dll is built in debug mode.
The binary System.Threading.ThreadPool.dll is built in debug mode.
The binary System.IO.FileSystem.Primitives.dll is built in debug mode.
The binary System.Runtime.dll is built in debug mode.

**Comment by tphaseitx** [comment]
Any advice please?

**Comment by coder2000** [comment]
I am working on making the library compatible with .NET Framework 4.5.2 and hopefully, that will fix this issue for you.

**Comment by tphaseitx** [comment]
Thank you very much for your response!
good luck and keep up with the great work you do!

**Comment by coder2000** [comment]
Version 3.0.2 has been released with .NET 4.5.2 support. Please give it a try and see if it resolves your issue. You may run into issues with signing that I am trying to fix as well but have limited resources to get a certificate so would appreciate any assistance.

**Comment by tphaseitx** [comment]
Updated to version 3.0.2. The same issues, binary xxxxx.dll is built in debug mode. The .DLL's are built in Release or x86 / Release? I don't know what the problem may be. I don't think it is a compatibility problem with a specific version of net Framework, the certification error message is that the library was built in Debug mode instead of Release mode.

The binary System.Globalization.Calendars.dll is built in debug mode.
The binary System.Threading.Tasks.Parallel.dll is built in debug mode.
The binary System.Xml.XmlDocument.dll is built in debug mode.
The binary System.Diagnostics.FileVersionInfo.dll is built in debug mode.
The binary System.IO.FileSystem.DriveInfo.dll is built in debug mode.
The binary System.Net.Ping.dll is built in debug mode.
The binary System.ComponentModel.Primitives.dll is built in debug mode.
The binary System.Net.NameResolution.dll is built in debug mode.
The binary System.ComponentModel.dll is built in debug mode.
The binary System.Runtime.InteropServices.dll is built in debug mode.
The binary System.Diagnostics.Process.dll is built in debug mode.
The binary System.Collections.Concurrent.dll is built in debug mode.
The binary System.Reflection.Primitives.dll is built in debug mode.
The binary System.Text.Encoding.dll is built in debug mode.
The binary System.Reflection.dll is built in debug mode.
The binary System.IO.UnmanagedMemoryStream.dll is built in debug mode.
The binary System.IO.IsolatedStorage.dll is built in debug mode.
The binary System.Net.WebSockets.Client.dll is built in debug mode.
The binary System.Resources.Reader.dll is built in debug mode.
The binary System.Linq.Parallel.dll is built in debug mode.
The binary System.Collections.dll is built in debug mode.
The binary System.Linq.dll is built in debug mode.
The binary System.Diagnostics.Contracts.dll is built in debug mode.
The binary System.Diagnostics.Tools.dll is built in debug mode.
The binary System.Collections.NonGeneric.dll is built in debug mode.
The binary System.Linq.Expressions.dll is built in debug mode.
The binary System.Runtime.Handles.dll is built in debug mode.
The binary System.Net.Security.dll is built in debug mode.
The binary System.Threading.Timer.dll is built in debug mode.
The binary System.ComponentModel.EventBasedAsync.dll is built in debug mode.
The binary System.Net.WebHeaderCollection.dll is built in debug mode.
The binary System.IO.FileSystem.Watcher.dll is built in debug mode.
The binary Ubiety.StyleCop.dll is built in debug mode.
The binary System.Runtime.CompilerServices.VisualC.dll is built in debug mode.
The binary Microsoft.Win32.Primitives.dll is built in debug mode.
The binary System.Runtime.Extensions.dll is built in debug mode.
The binary System.Text.Encoding.Extensions.dll is built in debug mode.
The binary System.Security.Principal.dll is built in debug mode.
The binary System.Globalization.dll is built in debug mode.
The binary System.ObjectModel.dll is built in debug mode.
The binary System.Collections.Specialized.dll is built in debug mode.
The binary System.IO.Compression.ZipFile.dll is built in debug mode.
The binary System.AppContext.dll is built in debug mode.
The binary System.Diagnostics.TraceSource.dll is built in debug mode.
The binary System.Security.Claims.dll is built in debug mode.
The binary System.Console.dll is built in debug mode.
The binary System.IO.Pipes.dll is built in debug mode.
The binary System.Linq.Queryable.dll is built in debug mode.
The binary System.Security.Cryptography.Csp.dll is built in debug mode.
The binary System.Security.Cryptography.Primitives.dll is built in debug mode.
The binary System.IO.dll is built in debug mode.
The binary System.Dynamic.Runtime.dll is built in debug mode.
The binary System.Net.NetworkInformation.dll is built in debug mode.
The binary System.Security.Cryptography.X509Certificates.dll is built in debug mode.
The binary System.Resources.Writer.dll is built in debug mode.
The binary System.Net.Primitives.dll is built in debug mode.
The binary System.Net.Requests.dll is built in debug mode.
The binary System.Runtime.Serialization.Formatters.dll is built in debug mode.
The binary System.Runtime.Numerics.dll is built in debug mode.
The binary System.Xml.XmlSerializer.dll is built in debug mode.
The binary System.Resources.ResourceManager.dll is built in debug mode.
The binary System.IO.FileSystem.dll is built in debug mode.
The binary System.ComponentModel.TypeConverter.dll is built in debug mode.
The binary System.Text.RegularExpressions.dll is built in debug mode.
The binary System.Diagnostics.TextWriterTraceListener.dll is built in debug mode.
The binary System.Threading.Thread.dll is built in debug mode.
The binary System.Drawing.Primitives.dll is built in debug mode.
The binary System.IO.MemoryMappedFiles.dll is built in debug mode.
The binary System.Threading.dll is built in debug mode.
The binary System.Xml.XDocument.dll is built in debug mode.
The binary System.Net.WebSockets.dll is built in debug mode.
The binary System.Diagnostics.Debug.dll is built in debug mode.
The binary System.Security.Cryptography.Encoding.dll is built in debug mode.
The binary System.Xml.XPath.dll is built in debug mode.
The binary System.Runtime.Serialization.Json.dll is built in debug mode.
The binary System.Xml.ReaderWriter.dll is built in debug mode.
The binary System.Reflection.Extensions.dll is built in debug mode.
The binary System.Threading.Tasks.dll is built in debug mode.
The binary System.Threading.ThreadPool.dll is built in debug mode.
The binary System.IO.FileSystem.Primitives.dll is built in debug mode.
The binary System.Runtime.dll is built in debug mode.

**Comment by tphaseitx** [comment]
At the beginning the first message was
"Ubiety.Dns.Core.dll is built in debug mode""

After that I had removed the reference of Ubiety.Dns.Core that was installed with the MySQL.Data package and installed the official Ubiety.Dns.Core package from NuGet, version 2.5.0.

And now the 3.0.2.

Since upgrading to the version 2.5.0 (and now 3.0.2) I don't get the 
"Ubiety.Dns.Core.dll is built in debug mode" error message,

I get that message abowe (all those DLL's that are built in Debug mode)

**Comment by coder2000** [comment]
That is weird as if you look at the build logs the library is built in Release mode, and I don't know why it would be affecting all of the framework libraries. Try clearing your bin and obj folders and try building again.

**Comment by tphaseitx** [comment]
>> I already did that many times.

Yes it is weird, I am sure the Ubiety.Dns.Core is built in Release mode.
Removing MySql.Data and Ubiety.Dns.Core (because removing only Ubiety.Dns.Core alone cause MySql.Data to add the Ubiety.Dns.Core by default in my project) and that loooong list of DLL's built in Debug mode error is gone.

**Comment by coder2000** [comment]
Oracle includes the library in their package so it may have been a conflict in the version MySql.Data was expecting versus what was available when loading it separately. I am trying to work with them on using my library as a dependency but they are non-responsive.

**Comment by tphaseitx** [comment]
It is strange because MySql.Data.dll is not marked as being built in Debug mode. I can't figure it out what the problem may be.

**Comment by coder2000** [comment]
Is this still an issue?
